# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

In [2]:
import numpy as np 

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1.1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [52]:
print(np.loadtxt(r'C:\Users\Саня\Downloads\minutes_n_ingredients.csv', dtype='int32', delimiter=',', skiprows=1)[:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [4]:
arr = np.loadtxt(r'C:\Users\Саня\Downloads\minutes_n_ingredients.csv', dtype='int32', delimiter=',', skiprows=1)
print(f"2-й столбец: Среднее: {np.mean(arr[:, 1])}, Мин: {np.amin(arr[:, 1])}, Макс: {np.amax(arr[:, 1])}, Медиана: {np.median(arr[:, 1])}")
print(f"3-й столбец: Среднее: {np.mean(arr[:, 2])}, Мин: {np.amin(arr[:, 2])}, Макс: {np.amax(arr[:, 2])}, Медиана: {np.median(arr[:, 2])}")

2-й столбец: Среднее: 21601.00169, Мин: 0, Макс: 2147483647, Медиана: 40.0
3-й столбец: Среднее: 9.05528, Мин: 1, Макс: 39, Медиана: 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [54]:
print(f"квантиль = {np.quantile(arr[:, 1], q=0.75)}")
print(arr[arr[:, 1]<65.0])

квантиль = 65.0
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [371794     35      8]
 [ 43407     35      7]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [63]:
from collections import Counter
#print(f"Продолжительность равная нулю: {Counter(arr[:, 1] == 0)[True]}") 
m1 = arr2[:, 1] == 60
m2 = arr2[:, 2] == 16
m3 = m1*m2
print(np.count_nonzero(m3))
arr2 = arr.copy()
arr2[arr2[:, 1] == 0] += [0, 1, 0]

121


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [56]:
print(len(np.unique(arr[:, 0])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [76]:
print(len(np.unique(arr[:, 2])))
ag = np.unique(arr[:, 2], return_counts=True)
print(f"Значения: {ag[0]}\nКол-во: {ag[1]}")

37
Значения: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
Кол-во: [   13   926  2895  5515  7913  9376 10628 10951 10585  9591  8297  6605
  4997  3663  2595  1767  1246   790   573   376   217   161   105    69
    50    28    16    16    12    12     3     1     2     1     3     1
     1]


## Лабораторная работа №1.2

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [12]:
arr[arr[:, 2] <= 5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [48]:
arr3 = arr.copy()
arr3 = np.c_[arr3, np.zeros(np.shape(arr)[0])]
arr3 = arr3.astype(float, copy=False)
arr3[:,3] += np.divide(arr3[:, 2], arr3[:, 1], out=arr3[:, 2], where=arr3[:, 1] != 0)
print(arr3)

[[1.27244000e+05 6.00000000e+01 2.66666667e-01 2.66666667e-01]
 [2.38910000e+04 2.50000000e+01 2.80000000e-01 2.80000000e-01]
 [9.47460000e+04 1.00000000e+01 6.00000000e-01 6.00000000e-01]
 ...
 [4.98432000e+05 6.50000000e+01 2.30769231e-01 2.30769231e-01]
 [3.70915000e+05 5.00000000e+00 8.00000000e-01 8.00000000e-01]
 [8.19930000e+04 1.40000000e+02 1.00000000e-01 1.00000000e-01]]


In [64]:
np.amax(arr3[:,3])

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [31]:
arr_sort = arr[arr[:, 1].argsort()] # sort arr
arr_sort_100 = np.flipud(arr_sort) #reverse
print(np.sum(arr_sort_100[:100, :], axis=0)[2]/100)

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [43]:
ind = np.random.randint(100000, size=10)
print(ind)
print(arr[ind, :])

[28509 69582 85483 48287  4406 98451 10856 20905 49660 40635]
[[324444     50     11]
 [ 76983     35      5]
 [361683     50     15]
 [ 27033    105     10]
 [ 99817     10      8]
 [  7086      5      8]
 [167746    205     16]
 [180645     15      7]
 [ 62665     25      9]
 [363874     35     14]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [14]:
print(np.sum(arr, axis=0)[2]/arr.shape[0]) # среднее значение
print(np.sum(arr[:, 2] < np.mean(arr[:,2]))/arr.shape[0]*100)

9.05528
58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [76]:
arr_simple = arr.copy()
arr_simple = np.c_[arr_simple, np.zeros(np.shape(arr)[0], dtype='int64')] # соединяет два массива вдоль ОY 
arr_simple[np.logical_and((arr_simple[:, 1] <= 20), (arr_simple[:, 2] <= 5))] += [0, 0, 0, 1]
print(*arr_simple, sep='\n')

[31714    20     5     1]
[350905     20      8      0]
[375553     15      5      1]
[189013     22     14      0]
[71443    25     3     0]
[35474   490    17     0]
[117604     90      5      0]
[36875    25     8     0]
[10087   165     9     0]
[257499      5     10      0]
[307174     12      6      0]
[267908     40      4      0]
[442201     20     10      0]
[407431     75     12      0]
[55796    22    12     0]
[469508     50      5      0]
[339337     30      7      0]
[454387     30     10      0]
[25384    30     9     0]
[21768    55    13     0]
[162508     15      7      0]
[112035     45      9      0]
[12299    25    10     0]
[16434   100     7     0]
[450804    105     12      0]
[441459     40     10      0]
[323574    120      7      0]
[265853    200      8      0]
[336213     45     13      0]
[170232     11      9      0]
[165961      6      7      0]
[342340     65     16      0]
[183135   1455      8      0]
[66843     3     9     0]
[134000     60     11   

[257127     25      3      0]
[90228    30    11     0]
[335229     37     11      0]
[311023     10      7      0]
[398770     50      4      0]
[106571      7      4      1]
[282989     50     16      0]
[412475    100     13      0]
[226749    240      9      0]
[470077    255     15      0]
[140780     65      7      0]
[115751     50     10      0]
[372908     85      8      0]
[496625     40     10      0]
[414354     50     13      0]
[14501    30     5     0]
[444294    109     10      0]
[398499     35      9      0]
[449103     90      4      0]
[52444    40     6     0]
[142644     45     11      0]
[47677    15     3     1]
[287657    330     11      0]
[201460     30     10      0]
[82098  1500    14     0]
[445002     20     12      0]
[188171     40      8      0]
[16110    35     9     0]
[305365     15      7      0]
[48576   195     9     0]
[402541    110      7      0]
[272320     22      6      0]
[156582     15      8      0]
[62545    57    15     0]
[379905     

[423850      3      6      0]
[44739    35     5     0]
[235350     80      9      0]
[312160      5      4      1]
[116543     25     10      0]
[398595     90     11      0]
[78897    40     8     0]
[45834    75    10     0]
[103803     60     11      0]
[464753     50      9      0]
[140651     20      7      0]
[127652     50     12      0]
[393601     45      7      0]
[449705     30     16      0]
[388625    200      9      0]
[92208    15    11     0]
[196085     27      9      0]
[156383     30     10      0]
[260535     30      5      0]
[396477     20      9      0]
[205276     50     10      0]
[44002    21     6     0]
[208870     30      6      0]
[350547     30      9      0]
[300108     15     11      0]
[95046    15     6     0]
[121599     16      8      0]
[263631     42     10      0]
[410116   1500     12      0]
[164312     80     14      0]
[373172     95     11      0]
[474619     75     17      0]
[302598    110     12      0]
[77878   490    14     0]
[475843 

[178337     13      9      0]
[258090    490      5      0]
[200420      3      4      1]
[210530     45      5      0]
[111376     45      6      0]
[317077     10      3      1]
[97474   110    28     0]
[138078     35      9      0]
[93463  1590     5     0]
[371864     30     11      0]
[67063  1800     5     0]
[12169    40     7     0]
[302004     35     11      0]
[196070     15      6      0]
[306126     20     12      0]
[229867     25     11      0]
[3116   90   24    0]
[254508     20      6      0]
[403574     12      7      0]
[144005    140     19      0]
[209559      5      3      1]
[136868     50      8      0]
[115095      5      2      1]
[362546     40      3      0]
[185796    120     15      0]
[430102      5      5      1]
[440738     65     14      0]
[137208    105     12      0]
[97128    70     9     0]
[140422     30      5      0]
[150044     40     14      0]
[194954     65     12      0]
[232106     70      8      0]
[359346     10      4      1]
[332519 

[221799     15      9      0]
[305070     40     14      0]
[32458     5     9     0]
[466271     20      5      1]
[136096     30     11      0]
[182678     75     18      0]
[67941    15    13     0]
[307155    495      8      0]
[302048      6      4      1]
[474921     40     13      0]
[260952     85     10      0]
[8437   50   10    0]
[369817     60     19      0]
[269055     42     13      0]
[18001    15     8     0]
[779  40   9   0]
[455920     22      5      0]
[192056    200      9      0]
[108907     55     12      0]
[307305      5      5      1]
[62940    35     9     0]
[206215     80     11      0]
[143301     10      6      0]
[334317     90      9      0]
[207840     10      6      0]
[229692     70     10      0]
[182098      5      4      1]
[356891     25     10      0]
[263795     90     12      0]
[282785     10      6      0]
[126325     65      6      0]
[275461     25     10      0]
[17825    40     9     0]
[102926     60     12      0]
[332642     35     1

[448591   2940      4      0]
[178968    120     16      0]
[10455   105    10     0]
[11754    30    11     0]
[190592    140     12      0]
[151746     80      6      0]
[359857     22      9      0]
[243769     60      6      0]
[210528     70      3      0]
[130664     50      6      0]
[342030     30      6      0]
[135701     35     10      0]
[387930     60     10      0]
[14825    85    10     0]
[183856    165     12      0]
[436371     63      9      0]
[24686    25    13     0]
[499490     45     17      0]
[100076     70      9      0]
[474007    305      7      0]
[231637     70      4      0]
[203659     50     22      0]
[94737     2     7     0]
[26915    50     6     0]
[111623     30      9      0]
[201231     65      9      0]
[342649    100     11      0]
[117363     14      9      0]
[116238     10      5      1]
[41081    15     6     0]
[60003     5     3     1]
[227044      5      3      1]
[278374     40     10      0]
[246286    135     18      0]
[28500    40

[286558     32     11      0]
[455249     40     12      0]
[31371    30     4     0]
[284214    135     10      0]
[56186    50     7     0]
[105492     20     13      0]
[255260     25      7      0]
[11291    95    11     0]
[389534     50      6      0]
[184845    120      7      0]
[437708    125     15      0]
[29756    55     7     0]
[326351     17     13      0]
[368566     10     11      0]
[34855    45     8     0]
[91952    90    12     0]
[121038     50      5      0]
[370833    125     12      0]
[46713    30     5     0]
[488024     35     12      0]
[80616    55     7     0]
[141531     30      7      0]
[26406    35     8     0]
[466836    420     24      0]
[335938     45     13      0]
[408091     10      7      0]
[84494   380     6     0]
[272305     48     16      0]
[248075     30     11      0]
[112173     60     14      0]
[344530     50      9      0]
[373386     20      8      0]
[102237     28      8      0]
[113725     80      8      0]
[362536    270     1

[49174    30     3     0]
[382052     10     10      0]
[364368    110     11      0]
[111456     80      3      0]
[26341    65    10     0]
[501626    300      9      0]
[146766     35      6      0]
[428806    130      7      0]
[66815    75     8     0]
[140757     18     10      0]
[256342     10     10      0]
[152944     40     11      0]
[444672     75     14      0]
[26939    35    12     0]
[60238    45     9     0]
[321077     40     10      0]
[483588    105     13      0]
[181389     50      5      0]
[68419    15     8     0]
[496827     30      7      0]
[445091     45      8      0]
[77997    20     6     0]
[225702     45      9      0]
[368308     25     12      0]
[351087     60      7      0]
[66923   120     6     0]
[212092     40      8      0]
[500102     74     12      0]
[315059     70     10      0]
[227078      2      6      0]
[57669    60     9     0]
[74365    25    10     0]
[337945     15      9      0]
[35563    68     8     0]
[311380     75     10   

[69818   360     7     0]
[455177     80      7      0]
[62992    12     7     0]
[285602     35      8      0]
[507317     25      9      0]
[245095     90     13      0]
[128496     80      9      0]
[290814     55      5      0]
[110133     55     17      0]
[330912    375     17      0]
[80784    40    11     0]
[107394     75      8      0]
[178196     65     16      0]
[363726     25     12      0]
[442459     30      5      0]
[221590     30     10      0]
[408734    110     14      0]
[58750     5     3     1]
[508241     20      8      0]
[184381     45      9      0]
[86115    30    11     0]
[401127     10      3      1]
[395558     30      6      0]
[409252     50     10      0]
[302720     25      6      0]
[32050    15     8     0]
[106826     25     10      0]
[413121     30      8      0]
[52780    70     9     0]
[128512     20     15      0]
[178109     30     12      0]
[157545     26      4      0]
[10322   390     9     0]
[299453     90      8      0]
[18117    80

[275146     60      8      0]
[454071     85     14      0]
[36366    70     8     0]
[461074     65     12      0]
[46072    50     8     0]
[212084     75      5      0]
[324462    275     14      0]
[349919     25      7      0]
[482189     90      7      0]
[92428    15     8     0]
[308563    735     10      0]
[222673     90      7      0]
[394910     45      9      0]
[172066     10      7      0]
[216242     65      8      0]
[269778     40      4      0]
[42754     5    10     0]
[173551     15      4      1]
[69134    22     5     0]
[149088     90     13      0]
[425065     25      8      0]
[27339   120    11     0]
[62552    75    10     0]
[271026     45     12      0]
[135442      4      4      1]
[356168     25      7      0]
[182860     10      5      1]
[52834    25     6     0]
[128504     35     17      0]
[366366     45      5      0]
[408699    370      9      0]
[97288   270     8     0]
[32979    20     9     0]
[283219     20      5      1]
[491557     45      

[293230     21      5      0]
[103799     30     11      0]
[99300    50     5     0]
[326818     35      8      0]
[71838    70    11     0]
[223870    190      8      0]
[303316     34      9      0]
[188432     60     11      0]
[242222     26     10      0]
[149984   1110     15      0]
[14888    25    10     0]
[383241     35     13      0]
[235096    126      5      0]
[102779     55     11      0]
[61389    25     8     0]
[330922    495     18      0]
[292363     25      8      0]
[482128     45     12      0]
[453747    120      7      0]
[367531      2      6      0]
[513545     40      8      0]
[11007   325     8     0]
[240134     50      7      0]
[373651     33     13      0]
[108055     45      5      0]
[86971    50     9     0]
[475237    250      4      0]
[105565    325     15      0]
[38090    15    11     0]
[344999     15     14      0]
[408757     40     10      0]
[415219      5      6      0]
[306149     60      6      0]
[454477     60     16      0]
[182996 

[301624     10      8      0]
[183003     43     11      0]
[345704     10      4      1]
[226188     20      9      0]
[85648    30     9     0]
[65808   435    19     0]
[324239     90     10      0]
[64485    28    13     0]
[162592     10      5      1]
[56114    27     5     0]
[51333    12    10     0]
[157106    105     13      0]
[496754     42      5      0]
[408686     15     14      0]
[204146     45     17      0]
[184235      5      3      1]
[295879     90     16      0]
[289866     42     14      0]
[28975    85    11     0]
[9286   20    7    0]
[228628     45     11      0]
[47434    55     6     0]
[497159     33      8      0]
[113283     35      5      0]
[78567    85    11     0]
[428049     80     11      0]
[109748     30      3      0]
[325944     80     10      0]
[514757     20      5      1]
[36130    65    11     0]
[370306     20     10      0]
[76185    80    10     0]
[133201     21     10      0]
[32093    30     4     0]
[501887     25      3      0]
[2

[407882     50     12      0]
[251106    130      9      0]
[98169   140     7     0]
[288045     93     11      0]
[233102     55      8      0]
[356431     20      6      0]
[109028     45      7      0]
[110399     75     12      0]
[57877    50    10     0]
[364374      5      4      1]
[70997    80     6     0]
[411839     15      8      0]
[495346     35     12      0]
[22156    35     4     0]
[137495     55      9      0]
[454973     10      6      0]
[20311    40     8     0]
[66233    80    12     0]
[342961     10      2      1]
[42704    75     8     0]
[47465    70    13     0]
[331044     45     14      0]
[319373    380      5      0]
[493112    100     14      0]
[347969     60      7      0]
[98076     5     3     1]
[437  25   5   0]
[30274   205    11     0]
[59353    65     2     0]
[317235      5      6      0]
[118906      4      2      1]
[355495     15      6      0]
[57971    18    12     0]
[195084     15     10      0]
[379320     10      9      0]
[8857   60

[205020     10      6      0]
[87910    45    14     0]
[403975     55      6      0]
[152074     45     11      0]
[313056     45      9      0]
[109039     35      7      0]
[456737     10      9      0]
[251093     40      5      0]
[116528     45     10      0]
[133212     40      5      0]
[62998    60     7     0]
[169400     50     12      0]
[449807     15     15      0]
[240093     15      9      0]
[186480      2      4      1]
[213093     15     10      0]
[495524     40      5      0]
[234012     25      4      0]
[39839    32    14     0]
[515426    510     10      0]
[104322     40      8      0]
[43370    22     9     0]
[477885     30      5      0]
[71649    70     5     0]
[364216     35      6      0]
[513064   1230      8      0]
[290957     13      8      0]
[47287   105    12     0]
[225349     15     11      0]
[262311     40      3      0]
[62602     7     9     0]
[102214     35     14      0]
[66126    35    13     0]
[134820     25     10      0]
[364525     

[62991    25    12     0]
[367949     80     13      0]
[284261     10     14      0]
[55711    25     8     0]
[224677     45      9      0]
[114046     75     11      0]
[53549    25    14     0]
[455750     10      4      1]
[136676     20      6      0]
[235229     80     12      0]
[145813     20     13      0]
[146112      8      5      1]
[377561     45     15      0]
[317850      2     25      0]
[107565     86     16      0]
[123609     45      8      0]
[288381    160     19      0]
[198027     35      6      0]
[239854     30      7      0]
[377554     45     11      0]
[10863  5770    10     0]
[183244     10      6      0]
[123295     75     11      0]
[282863    365      4      0]
[26533   130     6     0]
[239325     90      7      0]
[52689     5     6     0]
[129538     95      9      0]
[39277    15    10     0]
[99804    30    12     0]
[7919   30   12    0]
[302891     75      6      0]
[303109     60     12      0]
[183719     25     13      0]
[222785     10      

[288031     40     14      0]
[157285     80     13      0]
[427230     65     11      0]
[294067     30      8      0]
[311274     50     11      0]
[484584     35     11      0]
[233304     15      6      0]
[293628      5      7      0]
[229406      5     10      0]
[129926     45     10      0]
[323412     30      8      0]
[309706    130     12      0]
[84549    60     8     0]
[32047    18     9     0]
[325212     80     11      0]
[235420      8      2      1]
[143203     40      8      0]
[386261     65      5      0]
[8185   30    8    0]
[271584     75     11      0]
[367725     30     14      0]
[121006     25      6      0]
[310032     45      5      0]
[161819      5      5      1]
[152725     80     11      0]
[81394    75    13     0]
[15177    65    12     0]
[98000    15     3     1]
[135216     55      5      0]
[453403     20      6      0]
[81612    50    12     0]
[54665    30     8     0]
[257457     50     11      0]
[166317     60      7      0]
[67318   150    

[140217     30      6      0]
[211928     55     17      0]
[8199    0    6    0]
[27895    10     9     0]
[422152     30      9      0]
[43763    70     8     0]
[366850     40      6      0]
[394817     46      9      0]
[287376     11      4      1]
[123608     75     11      0]
[200633     23     11      0]
[10093    10     7     0]
[84517   130     9     0]
[41890    40    19     0]
[420761     10      6      0]
[154782     20      6      0]
[236461    205     11      0]
[196286    315     11      0]
[197128     75     12      0]
[475047     10      8      0]
[244360     55      7      0]
[164639     46      9      0]
[20397    40    14     0]
[88781    15     6     0]
[183702     60     10      0]
[335570      2      5      1]
[14512    35     4     0]
[127295     30      9      0]
[412386     25     14      0]
[133595     38      9      0]
[109434     30     10      0]
[51884    25    11     0]
[497751      5      3      1]
[98863    30    11     0]
[383349     40     11      0

[270752     25      6      0]
[ 91 150  13   0]
[344265     30      8      0]
[160596    150     13      0]
[180650     95     10      0]
[225621    105      9      0]
[226355     95     14      0]
[168123      5      9      0]
[156137     35      7      0]
[170696     55     10      0]
[288273     20     13      0]
[304303     50     11      0]
[141318     85      9      0]
[37876    35     7     0]
[285523     55      7      0]
[13723    22     7     0]
[227111     10      5      1]
[150284    190     11      0]
[20904    50     7     0]
[310855     25      8      0]
[269992     40      7      0]
[245986   1470      5      0]
[517885     30     14      0]
[436678     35     15      0]
[55179    40     8     0]
[408154    320     12      0]
[172405     46     13      0]
[112205     40      8      0]
[295501     55      9      0]
[386675    390      8      0]
[189816    270     12      0]
[135522     35     11      0]
[206872     60      6      0]
[34029    15     7     0]
[54905    25

[13183   530     8     0]
[219569     20      9      0]
[277838    375     14      0]
[417325     65      9      0]
[163210     45     13      0]
[151857     40     13      0]
[207288    485      9      0]
[182955     90     11      0]
[273267     20      9      0]
[111987    130      4      0]
[251343     30     12      0]
[364730     35      6      0]
[230158     25      6      0]
[579 380  13   0]
[397706     15      7      0]
[306376     15      7      0]
[192922     55     12      0]
[207974     10      6      0]
[392826     25     11      0]
[353694     45     15      0]
[447014     10      6      0]
[357601     15      4      1]
[505931     35      7      0]
[458300     32     12      0]
[35659    53    10     0]
[482313     35     18      0]
[83693    55    11     0]
[140781     30      6      0]
[309458     35      8      0]
[76843    55     6     0]
[84120    25    10     0]
[482842     55      8      0]
[121173     90     12      0]
[398200     50     12      0]
[412075    1

[171524     40     11      0]
[210700     25      9      0]
[88898    95    12     0]
[360213    150     17      0]
[377441      6      3      1]
[277980     60     11      0]
[147172    620     14      0]
[223086     25      3      0]
[223485    135      6      0]
[126433     45      9      0]
[5185   90   14    0]
[384938     75     14      0]
[203637    225     12      0]
[80111    70     5     0]
[171226    140      7      0]
[373766      5      8      0]
[111467     65      6      0]
[302007     35      6      0]
[478030     30      8      0]
[161096     60     15      0]
[319684    430      6      0]
[43252    15     6     0]
[376679     55      6      0]
[70431    60    12     0]
[208539     80     15      0]
[97245   195     9     0]
[439143     70     15      0]
[201019     55      9      0]
[112324     50     10      0]
[173339    130     13      0]
[264881    485      6      0]
[276696     15      9      0]
[115236     15      9      0]
[361619     60     14      0]
[201347 

[123455     40      7      0]
[257795      5      8      0]
[54322   180    11     0]
[113594     40      7      0]
[120770     12      5      1]
[213385     25     16      0]
[188194     75      9      0]
[112380     70     12      0]
[192079     40      8      0]
[339204      5      7      0]
[72493    25    10     0]
[63907     5     6     0]
[64223    20    10     0]
[211823     20      9      0]
[3496    0    8    0]
[62793    45     9     0]
[54197    35     8     0]
[424665     20      6      0]
[124151     60     18      0]
[158604    195      9      0]
[226716      1      3      1]
[432038     40      8      0]
[61307    40    14     0]
[57252    35    12     0]
[96516    25    14     0]
[470562    250      8      0]
[146520    300     13      0]
[78150    75    13     0]
[212173     55     12      0]
[31115    60     7     0]
[73972    60    10     0]
[279983      2      2      1]
[471350     75     11      0]
[116902     40      5      0]
[244612     30      7      0]
[11730

[75308    20    10     0]
[518494     25     13      0]
[199071      5      4      1]
[9363   55    9    0]
[149391     60     15      0]
[336408     15     12      0]
[373181     15      4      1]
[114337     75     16      0]
[103402     10      5      1]
[14683    60    17     0]
[305025      2      4      1]
[210428     45     12      0]
[300107     17      9      0]
[493137     35      9      0]
[327024     30     16      0]
[154054    315     11      0]
[142197     75     10      0]
[47495   255     8     0]
[96104    35     8     0]
[117229     22     15      0]
[228676     55     16      0]
[364488     30      6      0]
[341069   2890      3      0]
[200493     30     14      0]
[293713     10      7      0]
[116387     20     12      0]
[11113   185     7     0]
[376630     35      6      0]
[193095     27     10      0]
[403205     20     15      0]
[362647     15      8      0]
[100247     60     14      0]
[410985    165     13      0]
[193661     20      9      0]
[489807 

[167040     60      6      0]
[134793     75     12      0]
[451607    250     11      0]
[457966     30     18      0]
[90767    20     8     0]
[380480    120     20      0]
[131643     30      8      0]
[376766     35     17      0]
[217895    380     11      0]
[179663    270      7      0]
[179664     50     12      0]
[76907    55     7     0]
[99666   145    15     0]
[56863     5     5     1]
[456472     40     10      0]
[380156     30     13      0]
[190864   1440      8      0]
[224056     25      7      0]
[91298    10     6     0]
[31952   135     5     0]
[457337      5      4      1]
[404208     60     12      0]
[181158     60     15      0]
[287282     12      6      0]
[283583     30      7      0]
[140151    150      7      0]
[79132    15     6     0]
[78303    80    11     0]
[263415     20      8      0]
[360011     35     11      0]
[8875    5    3    1]
[157578     30      6      0]
[232885    170     17      0]
[272235     10      6      0]
[184679    608      

[156134     40     12      0]
[107666      6      4      1]
[314928     55      9      0]
[223240     15      9      0]
[182773     15      5      1]
[451417     25      7      0]
[68732   110     3     0]
[63062    30     8     0]
[24287   200    15     0]
[300113     25      8      0]
[22472    20     8     0]
[41674  1490     5     0]
[501713     65     23      0]
[336882     65     11      0]
[123300    125      8      0]
[227385     26     10      0]
[391434     40      8      0]
[469308    100     16      0]
[1306  490   14    0]
[399430      9      5      1]
[152327     35      7      0]
[341990    150     12      0]
[412703     30      7      0]
[412984     35      8      0]
[213192      5      5      1]
[96237    50     9     0]
[12427    58    15     0]
[227777     75      9      0]
[361099     15      6      0]
[152639     60     12      0]
[250473     30      8      0]
[148085     75     10      0]
[304689     55      8      0]
[98412    70     8     0]
[16742    10     7  

[21122    30     9     0]
[396206     60      4      0]
[336583     50      9      0]
[240060    280      8      0]
[277350     30      8      0]
[203493    120      9      0]
[62252    60     7     0]
[212029     35      8      0]
[65976    60     7     0]
[41601    35     9     0]
[38876    55    12     0]
[260329     15     11      0]
[347955     75      5      0]
[482252    135      6      0]
[143345     55      7      0]
[91449    70     8     0]
[275114     75     14      0]
[204483      5     13      0]
[290205     52     10      0]
[16793    20     6     0]
[21344   100     5     0]
[459396     20      7      0]
[85787    65    11     0]
[221655     20     11      0]
[437400     75     13      0]
[113346     20      9      0]
[55876    10     5     1]
[252131     45     12      0]
[430398      5      4      1]
[365438    720      6      0]
[270187     20      8      0]
[145466    210     11      0]
[312195     25      8      0]
[81859     5     6     0]
[61682    30     5     0

[324977      3      4      1]
[162092    195     12      0]
[335975     20      6      0]
[456646     15      5      1]
[447114     10      8      0]
[411516      1      3      1]
[413821   1450      3      0]
[253848     10      7      0]
[210469     15      7      0]
[99009    25     8     0]
[130780     15      2      1]
[258290      7      7      0]
[17679    50     7     0]
[415408     55      7      0]
[97311     1     4     1]
[78005    35     8     0]
[293680     15      6      0]
[83825    65     5     0]
[6585   64   16    0]
[374604     30      9      0]
[230520     40      9      0]
[316375     45      9      0]
[364681     35      6      0]
[272414    300     24      0]
[356279     55     14      0]
[344452    170     15      0]
[425489    185      3      0]
[94479    20     4     1]
[185205     35     10      0]
[201970     35      6      0]
[43375    20     6     0]
[48500    40    12     0]
[331049     65      6      0]
[246210     35      9      0]
[63878    35    18  

[179148     60      3      0]
[191633     80     10      0]
[165664     60     14      0]
[232745     65     13      0]
[48123    70     9     0]
[262678     30      9      0]
[213965     40      6      0]
[159067     45     11      0]
[27739     5     7     0]
[474109     75      7      0]
[221324     55     10      0]
[237306     55      7      0]
[353962    120      8      0]
[127134     90     15      0]
[144724     90     11      0]
[99651    50    12     0]
[363612     70      8      0]
[279969     25      7      0]
[311252     20      7      0]
[179293     10      4      1]
[245489     30      8      0]
[30147    35     6     0]
[302729     40      8      0]
[280376    115      8      0]
[201981     40     16      0]
[54853    20     4     1]
[484901     15     11      0]
[328733     50      2      0]
[195866    255     13      0]
[355104      5      5      1]
[2630   20    7    0]
[350621     20      7      0]
[332803     30     10      0]
[481685      4      5      1]
[202009 

[403809     45      5      0]
[390614     25     10      0]
[191859     85     12      0]
[121905     75      8      0]
[90298     5     4     1]
[89121    25     4     0]
[330552     10     12      0]
[425729     30      9      0]
[170316     70      7      0]
[463748     40     13      0]
[269690     12      5      1]
[483592    140      7      0]
[343644    505     14      0]
[386540     25      8      0]
[51863   110     7     0]
[108843    255      5      0]
[123266    105     15      0]
[4711   25    6    0]
[354607    490     13      0]
[267500     20      6      0]
[102311     20      5      1]
[342033     40     11      0]
[302239     40     10      0]
[473880      5     13      0]
[461624     60     10      0]
[326835     90     10      0]
[54705    45    10     0]
[412505     25      7      0]
[382004     20     11      0]
[480338     55     19      0]
[333880     40     10      0]
[9028  365    6    0]
[251695     42      8      0]
[31910     5     4     1]
[449555     33  

[51448    10     7     0]
[38223    75     7     0]
[362820     15      5      1]
[407643     50     11      0]
[163570     40      8      0]
[418405     24      6      0]
[403375     22      8      0]
[82877    27     6     0]
[148096     90     12      0]
[361188    135      4      0]
[13315    15     3     1]
[310868    375     10      0]
[30676    20     5     1]
[351663     30      8      0]
[77945    33    14     0]
[337533     55      9      0]
[97693    10     5     1]
[102540     75      4      0]
[134804     18     11      0]
[437160     10      9      0]
[134082     35     12      0]
[506837     20      7      0]
[197530     40      3      0]
[69909    40     6     0]
[140690     80     11      0]
[26890    65     9     0]
[64687    50    10     0]
[382029     55      8      0]
[401954     60     19      0]
[292126     35     13      0]
[513258     23     12      0]
[8855   90    8    0]
[41155    20     6     0]
[411261     80     10      0]
[259891     20     10      0]
[2

[58747    15     5     1]
[178288      5      9      0]
[66304   120     5     0]
[209445     60      7      0]
[281416     40      7      0]
[91818   105    13     0]
[165101     90      7      0]
[103760     10      6      0]
[290604     10     10      0]
[253375     60     11      0]
[169561     30     15      0]
[295664     75      6      0]
[75336    27    10     0]
[190438     60     12      0]
[226074     55     10      0]
[367256     55      8      0]
[181529     60     11      0]
[184305     40     12      0]
[372423     10      9      0]
[35961    20    10     0]
[47247    29     9     0]
[248654     57     14      0]
[283440     40     12      0]
[175555     25     10      0]
[108918      5      9      0]
[255458     75     19      0]
[135952     30     14      0]
[137730      5      4      1]
[22389   195    13     0]
[117404     60     11      0]
[331991     45     10      0]
[120751     45     15      0]
[455279     20      6      0]
[454470    200     23      0]
[64641  

[137262     30     10      0]
[247160    250      4      0]
[216258     30     16      0]
[95512  1450     8     0]
[131690     25     19      0]
[185869     60     10      0]
[177340     30      9      0]
[320948     20      4      1]
[284447     50      8      0]
[250923     10      6      0]
[249250     50      8      0]
[98877    10     4     1]
[170093     75      9      0]
[215671     60     10      0]
[235580     10     11      0]
[28919   150    13     0]
[411537     90     11      0]
[120062    135     11      0]
[304660     10      4      1]
[282227     35      8      0]
[234952     40      9      0]
[276993     60     10      0]
[186449     20      4      1]
[123019     10      6      0]
[471325     10      7      0]
[36992   420     9     0]
[24155    28     7     0]
[96935     5     6     0]
[60524   510     7     0]
[312739     42      8      0]
[88543    10    12     0]
[441118      5      9      0]
[190326     75     14      0]
[111498     55      8      0]
[279210     

[505791     30      8      0]
[93620    90    16     0]
[74894    20     7     0]
[289389     80      8      0]
[255069    195     10      0]
[180338     30      7      0]
[261481     15      5      1]
[36830    95    10     0]
[32074    35     7     0]
[293430    140      5      0]
[211065     80     10      0]
[64565    16    13     0]
[120802     40     20      0]
[67878   150    19     0]
[403559      5      4      1]
[262340    110      8      0]
[480351    130      5      0]
[508112      8      4      1]
[359219      5      3      1]
[152310     75     20      0]
[270836     55      7      0]
[251183     20      9      0]
[78891    80     8     0]
[348433    210      7      0]
[423754     25      8      0]
[148952    375     11      0]
[294056    105      7      0]
[214393     25      7      0]
[61674    10     7     0]
[414785     20      7      0]
[17794    80    13     0]
[271800     40     15      0]
[331421     10      7      0]
[444700     90     11      0]
[296178     40  

[13279    50     7     0]
[465399     15      7      0]
[319859     14      9      0]
[73524    60     7     0]
[103216     75     13      0]
[40343    75     4     0]
[345196     40      7      0]
[402368    145      8      0]
[86159   245     8     0]
[408299     40      8      0]
[76930   210    11     0]
[473584     25     11      0]
[428533     27      7      0]
[336902     55      8      0]
[368682    435      8      0]
[338683     35     10      0]
[30502    55    12     0]
[349427     30     10      0]
[508578     20      4      1]
[280197      5      4      1]
[130754     45     13      0]
[388548     15      4      1]
[335777     75      8      0]
[68649    73    10     0]
[169784     90      5      0]
[340067     20     11      0]
[36266    17    11     0]
[232636     45      5      0]
[322010     70      8      0]
[195099    130     14      0]
[285628     45     11      0]
[45285    45     9     0]
[16678    70     9     0]
[271722     95     11      0]
[265717     40      

[229344      4      4      1]
[46147    25     7     0]
[391308      5      3      1]
[232629     45      9      0]
[235117     75      8      0]
[334011     50     10      0]
[348968    370      9      0]
[206391     20     15      0]
[393599     30      5      0]
[338033     75     12      0]
[472957     24      8      0]
[322025     55      9      0]
[151138      5      3      1]
[117412     10      6      0]
[171886     40      6      0]
[127144     10      5      1]
[395229   1500     14      0]
[24285   130    16     0]
[319692     40      9      0]
[167213     21      2      0]
[99272   170    10     0]
[54475   215     9     0]
[113883     40      9      0]
[75610    90    12     0]
[48012    65     6     0]
[318995     80     10      0]
[129997     10      8      0]
[455232     35     10      0]
[24379    35     8     0]
[423414     35      9      0]
[38479    50     4     0]
[14156    50     7     0]
[244935     55     11      0]
[139236     50      6      0]
[281030    125  

[83425     5     5     1]
[230899    600     10      0]
[70923    38     8     0]
[381742     67     11      0]
[164715     20      8      0]
[139651     65     10      0]
[301370     41     12      0]
[173825     30     10      0]
[278803     15      7      0]
[424553     75      5      0]
[307896     65      8      0]
[334056     90     12      0]
[478941      5      5      1]
[120094     60     12      0]
[286315     22      4      0]
[134494     55     13      0]
[225814     30     10      0]
[414903     50      9      0]
[57370    55    13     0]
[166471     45     13      0]
[76349    20     7     0]
[222099     25      6      0]
[184614     60     11      0]
[13920    50    10     0]
[176421     15      5      1]
[66259    15     8     0]
[236439     25      7      0]
[342778     35     10      0]
[18663    60    10     0]
[289169     50     13      0]
[105970     55      7      0]
[111766     25     14      0]
[297260     80     12      0]
[354750     70      7      0]
[296337 

[103248     25     11      0]
[318503     50      5      0]
[159011     55     14      0]
[466663     20      7      0]
[15846   182    13     0]
[313445     10      5      1]
[142388     25      8      0]
[378949    490      7      0]
[358830     25      4      0]
[263982    120     15      0]
[422656     45     15      0]
[182595     35      6      0]
[159969     10      6      0]
[15307    40     8     0]
[401186     90     18      0]
[211869     45      9      0]
[202238    210      8      0]
[398300     40     14      0]
[353258     23      6      0]
[420900     45     10      0]
[203946     10      3      1]
[8929    5    5    1]
[275489     55      8      0]
[115315     35     13      0]
[17732    60    10     0]
[60374    45    11     0]
[264586     55      8      0]
[108383     25      9      0]
[254906     25      5      0]
[266080     25      6      0]
[262813     60     14      0]
[505443      5      6      0]
[258575     35      9      0]
[107189     60     13      0]
[313

[3418    0   13    0]
[136903     20     12      0]
[420142    122      6      0]
[258561     50      5      0]
[302430     30      7      0]
[414484     40      7      0]
[477405     13      5      1]
[332 105   7   0]
[73412    75    10     0]
[88180    35     6     0]
[75819    25     8     0]
[450474     25      6      0]
[459235      2      7      0]
[191468     70      7      0]
[188817     60      8      0]
[313758     15      7      0]
[409757    220     12      0]
[48933    15     7     0]
[202876     50     16      0]
[115050    490      4      0]
[153239     60     15      0]
[52115     5     5     1]
[250694     40     11      0]
[246145     55     13      0]
[101074    220     11      0]
[70469    90     4     0]
[61936    60    12     0]
[97905    45     8     0]
[64169    30     8     0]
[190020    180     21      0]
[396632     20      6      0]
[468059    195     10      0]
[59969     5     2     1]
[325918      5      5      1]
[54983   250     7     0]
[105614    130

[281258     18      5      1]
[226047     10      6      0]
[272275    480     14      0]
[414389    320      9      0]
[29253   150     6     0]
[78310   140    12     0]
[36507    21     6     0]
[368102     40      5      0]
[191313    405     11      0]
[43094    80    11     0]
[61092    65    11     0]
[65190   110    14     0]
[626 115  12   0]
[108520      6      5      1]
[42038    15     3     1]
[91093    30     4     0]
[71185    85    14     0]
[172606     55      9      0]
[122082    270      9      0]
[139956    260     24      0]
[85825    75     9     0]
[457832      5      9      0]
[479414     70     12      0]
[427762     40      9      0]
[247918     75      7      0]
[220439     15      4      1]
[234697     25     10      0]
[454517     20      9      0]
[7435  275   16    0]
[364244     10      6      0]
[405623     30      6      0]
[287982     25      5      0]
[335566      2      4      1]
[221222     45     12      0]
[356902     46     19      0]
[303321   

[199344     40      6      0]
[75037    20     8     0]
[345634     27     10      0]
[42987     0     4     1]
[407599    190     12      0]
[203390     10      3      1]
[405554     75      9      0]
[141392     12      7      0]
[453610     40     11      0]
[72534    30    11     0]
[147514     75     15      0]
[378393     30      8      0]
[39956     5     3     1]
[383354     45     19      0]
[180518     30      8      0]
[226604     10      9      0]
[113102     40      8      0]
[63250    30    12     0]
[347862     20      5      1]
[277116     38     14      0]
[346346    245      5      0]
[177548      5      6      0]
[291620     30      5      0]
[128646     60      9      0]
[225494     30      4      0]
[53949    45    11     0]
[36709    55    12     0]
[475510     45     16      0]
[247607     25     16      0]
[438533     60     17      0]
[396940     55     12      0]
[399822     45      5      0]
[18477    70    12     0]
[278806     40     13      0]
[184756    1

[373811    145      6      0]
[179203     20      7      0]
[500218     35      5      0]
[93183    15    12     0]
[276649     10      7      0]
[157162    150      7      0]
[319744     65      5      0]
[240781     70      7      0]
[387692     20      4      1]
[64288    30     4     0]
[232954     70      5      0]
[380551     27     12      0]
[68885    35     9     0]
[15967    45     7     0]
[254586     40     11      0]
[200170     50      4      0]
[113327    105      8      0]
[10411    70    14     0]
[32414    40    10     0]
[220264     50     11      0]
[188019      2      4      1]
[216412     20      7      0]
[119756      5      5      1]
[9814   60    9    0]
[53194     8     9     0]
[459554     10      5      1]
[21296   200    13     0]
[202746    510     12      0]
[31326    33     5     0]
[145167    115      9      0]
[90900    30     9     0]
[315276     37      9      0]
[60551    22     9     0]
[23279    40    15     0]
[223102     48     11      0]
[26390

[197911    615      8      0]
[106629     35      9      0]
[57666    30     7     0]
[364565     80     13      0]
[204447     90      9      0]
[114094     30      6      0]
[41145    40     7     0]
[20884    17     9     0]
[215515     30     15      0]
[81118   210    12     0]
[72855    60    10     0]
[30286    60     8     0]
[278096     30     10      0]
[429805     30      7      0]
[333744     40     10      0]
[270545     20     11      0]
[155154     45      6      0]
[79770    83    14     0]
[103077     20      5      1]
[6594   45   10    0]
[353613      5      4      1]
[163349    490      7      0]
[201929     45      9      0]
[112001     85     23      0]
[3776    0   12    0]
[477009     25     10      0]
[356347     25      5      0]
[81086    30     5     0]
[353958     75     12      0]
[236145     55     11      0]
[145260     40      6      0]
[235939    105      9      0]
[352576     40     17      0]
[274602     25      3      0]
[334707      4      5      1

[145367      5      5      1]
[66110    35    11     0]
[319862     50     17      0]
[7773  135    8    0]
[345086     28     12      0]
[255680     25      6      0]
[128305     15      5      1]
[177872     65     10      0]
[300373     25      8      0]
[15646    80     8     0]
[59468    45    15     0]
[406318     35     14      0]
[324132     15      8      0]
[389657     35     10      0]
[237584      9     10      0]
[36575    10     3     1]
[113083    315      7      0]
[16889    30    10     0]
[428829     31      7      0]
[367782     15     11      0]
[308592    260     15      0]
[38606    85     7     0]
[144467     45      9      0]
[116727     60      5      0]
[54116    10     5     1]
[87786  1460     7     0]
[391012     30     13      0]
[21629     5     5     1]
[102295     65     12      0]
[284015     70      7      0]
[33440    27    18     0]
[241920     15      7      0]
[169870     90     13      0]
[7564   55   10    0]
[276991      7      5      1]
[91092

[324962     30     13      0]
[117091     55      7      0]
[100662    210     10      0]
[461946     12      9      0]
[357575     65      7      0]
[98974   130     5     0]
[77371     6     3     1]
[3933    0    6    0]
[155899     45      9      0]
[237806      5      5      1]
[200154     15     13      0]
[222074     60     13      0]
[211814     40      5      0]
[118399    100      7      0]
[314917     25      9      0]
[342195     15      4      1]
[15474    35    14     0]
[300057    125      3      0]
[40925    10     5     1]
[6676  122   11    0]
[121186     40     10      0]
[113536     65     11      0]
[135368    150     10      0]
[161158     60      8      0]
[221572     30      9      0]
[398811     30     10      0]
[274683     55      7      0]
[407740     70     16      0]
[363158     25     11      0]
[228887     10      9      0]
[124126     13      6      0]
[275943      6      6      0]
[43023    15     9     0]
[325141     35     13      0]
[274385     40  

[177667     70      4      0]
[129900     45      9      0]
[353610     35     10      0]
[27539   165    11     0]
[259385     50     14      0]
[137515     30     14      0]
[100010    170     14      0]
[217629    165     11      0]
[383410     50      7      0]
[320049     40     10      0]
[19099    90     6     0]
[279484     25      7      0]
[512511     30     13      0]
[94701    30     8     0]
[495477     60      8      0]
[476734     17      5      1]
[79380    55     8     0]
[97882    90     9     0]
[51979   320    11     0]
[349731     65     10      0]
[114413   1460     18      0]
[235547     10      6      0]
[140934     45      6      0]
[151660      5      5      1]
[89307    50     6     0]
[17383    20     8     0]
[332578     70     13      0]
[210487     40     17      0]
[123467     25      8      0]
[316735     10      7      0]
[172478     75     11      0]
[399610      2      5      1]
[375596     65     10      0]
[5436    0    6    0]
[138548     30     1

[48090     3     9     0]
[73940   100     8     0]
[295693     40      7      0]
[209160     70      7      0]
[175646     15      5      1]
[235312    205     10      0]
[118198     55     11      0]
[50989    10     9     0]
[82562    14     8     0]
[346354     40      9      0]
[198543     70     10      0]
[10533   330     6     0]
[99089    50     8     0]
[18302    30    15     0]
[47979    75     7     0]
[161644     30     11      0]
[244504     70      8      0]
[45693    65    12     0]
[96144     8     6     0]
[35393    23     8     0]
[422538      5      4      1]
[319680     65     12      0]
[410842     30      9      0]
[198272     25      7      0]
[471881     65     10      0]
[368238     70     16      0]
[4860    0   11    0]
[494507      6      6      0]
[49660    15     7     0]
[308327     30      8      0]
[186116     20      8      0]
[161778     60      5      0]
[320702     30     12      0]
[235171     50      7      0]
[321564      5      5      1]
[20608

[375045     35     10      0]
[146906     60      7      0]
[125856     75     12      0]
[177071     30     10      0]
[404359     40     14      0]
[202953    390     11      0]
[344914     80     12      0]
[65057    30    10     0]
[376804    195      9      0]
[188628    180     11      0]
[208478     15      6      0]
[400645     22     10      0]
[309439     20     10      0]
[45861    20     6     0]
[376890     25      8      0]
[343616     30      8      0]
[328438    300      6      0]
[52941    45    20     0]
[390145     40      7      0]
[56084    35    12     0]
[117211     55      9      0]
[133019    140      8      0]
[125910    100     10      0]
[121343      5      3      1]
[24889    70     6     0]
[76520    30     4     0]
[12634   430    14     0]
[140487      8      3      1]
[96847    70    11     0]
[303608     55      9      0]
[26611    60    10     0]
[187423     65      8      0]
[335639     40     17      0]
[119411     20      5      1]
[23936    32    

[8468   45    4    0]
[312448     13      8      0]
[348493      3      3      1]
[30785    30    11     0]
[293041     15      5      1]
[101141      2      2      1]
[31021    10     5     1]
[291715      5      4      1]
[62500   615     8     0]
[128085     60      8      0]
[177186      5      4      1]
[41788    30    12     0]
[429033     10      8      0]
[36253    50    11     0]
[134280     70      6      0]
[367230     25      9      0]
[5247    1    3    1]
[55141    65    12     0]
[49435    30    11     0]
[429679     15      5      1]
[31819    35     9     0]
[66834    50     7     0]
[77600    12     8     0]
[68134    90     8     0]
[117787     75      3      0]
[56661   300    12     0]
[288440     30      9      0]
[415598     35      6      0]
[304145     45      9      0]
[231540     15      6      0]
[214428     22     11      0]
[292743     45     12      0]
[33089   250     7     0]
[36148     2     5     1]
[95926     5     3     1]
[257289     50     10     

[160981     35      8      0]
[504281     35     10      0]
[480466     30      5      0]
[211972     30      6      0]
[200990     45     10      0]
[139952     35      7      0]
[351195     25      8      0]
[270116     75     11      0]
[285156     75      7      0]
[282570     40      9      0]
[409857     50      6      0]
[423152     15      8      0]
[90617    55    13     0]
[52700    25    11     0]
[98313    87     7     0]
[169922     60     12      0]
[239933     90      4      0]
[47893    40    15     0]
[37526   270     6     0]
[413590     20     15      0]
[173234     75      3      0]
[15969    15     8     0]
[132689     75      9      0]
[356317     30     10      0]
[82900    30     9     0]
[370418     55      6      0]
[344764     30      9      0]
[377414     40      7      0]
[251641     20      6      0]
[196113     80      7      0]
[121819     40      8      0]
[70837    55    10     0]
[170385     10      6      0]
[217147     30     15      0]
[303433     

[15891    25     6     0]
[7786    0    9    0]
[277222     60      5      0]
[77863    45    10     0]
[325741     15      3      1]
[83071   110    18     0]
[159018     30      8      0]
[50983   270    17     0]
[95100    80    11     0]
[114086     30      8      0]
[405602     75      7      0]
[370406     15      6      0]
[96321    40     9     0]
[302624     45      6      0]
[167890     30      9      0]
[315053     35     10      0]
[463292     55     13      0]
[18962   620    11     0]
[139987      5      4      1]
[162422     61     15      0]
[327983    135     10      0]
[295642     68     11      0]
[99930     5     8     0]
[133604    210     13      0]
[114671    120     20      0]
[411682     20      7      0]
[489  71   5   0]
[88422    20     7     0]
[324267     15      4      1]
[132476      7      6      0]
[323951     40     10      0]
[168670    550      5      0]
[103078     65      8      0]
[104433     10     10      0]
[384197     24      7      0]
[31335

[206666     15      9      0]
[293735     10      5      1]
[188027     27      6      0]
[195696     65     10      0]
[261511     20     11      0]
[239051     25      9      0]
[273356     30      4      0]
[127048     35      9      0]
[459487     20     12      0]
[177479     10      5      1]
[417064     20     13      0]
[11647    15     5     1]
[11015    21     6     0]
[114801      5      5      1]
[35649    15     5     1]
[261635     45     10      0]
[508582     48      6      0]
[65538   500    13     0]
[285735     20     11      0]
[96973    30    10     0]
[438284     50      7      0]
[130385      5      6      0]
[97867     2     7     0]
[135948     10      5      1]
[324824     25      4      0]
[25329    25    10     0]
[54900  3360    10     0]
[257673     30     12      0]
[161966     20      9      0]
[134773      5      3      1]
[114281     45      6      0]
[41127    20     3     1]
[237412     70     11      0]
[69250   105    16     0]
[211838     38      

[13528    20     5     1]
[55185   335    12     0]
[131671    102      7      0]
[303171     40      6      0]
[389057     35      8      0]
[100286    615      7      0]
[262886     40      7      0]
[236689     13     17      0]
[88475    70     7     0]
[415154     50      5      0]
[39100    41    10     0]
[257737     55     11      0]
[147381     70      8      0]
[107602     10      6      0]
[120205      5      5      1]
[189218     23     10      0]
[225343     10      7      0]
[96087    15     4     1]
[22872    35     6     0]
[279935     45     12      0]
[31182    75    17     0]
[469632     20     10      0]
[355374     33     13      0]
[193642     12      6      0]
[29987    20     5     1]
[447121     15     14      0]
[456236     40      6      0]
[385516     28     13      0]
[474394     25      6      0]
[47989    25     9     0]
[93524    85    10     0]
[174171     15      4      1]
[240676     30     12      0]
[95352    60    17     0]
[110885    365      4   

[79335    65     5     0]
[79483    28     5     0]
[474549    405     15      0]
[92620    30    10     0]
[333883    165     11      0]
[436352     30     11      0]
[275612     45      7      0]
[215342     70     14      0]
[166347     40     10      0]
[240698     30     12      0]
[27246   230     9     0]
[326731     25      6      0]
[28670    30    12     0]
[232946     50      8      0]
[200481     40     20      0]
[20165     5     5     1]
[246655     25     14      0]
[320035     35     15      0]
[193065     25      7      0]
[22243   260     6     0]
[177150     30      7      0]
[8726   55    8    0]
[221722     70     13      0]
[222726     10      4      1]
[334751     25     15      0]
[76923    60    13     0]
[376817     10      6      0]
[461289     25     12      0]
[348591     30      8      0]
[6863    0   10    0]
[91248   365     8     0]
[179598     25     10      0]
[319543    190     17      0]
[261807      5      6      0]
[41292    48    10     0]
[12148

[45735    30     5     0]
[155748     50      7      0]
[105866     55      7      0]
[177760     70      6      0]
[412417    110     12      0]
[467353     60     13      0]
[381375     10      6      0]
[288427    275     16      0]
[284679     20      9      0]
[28487    25    13     0]
[11689    50    10     0]
[392138     30      7      0]
[63212    60    11     0]
[385381     80     11      0]
[464121     50     10      0]
[102473     20     13      0]
[171929     40     13      0]
[48834    55    10     0]
[292244     31     12      0]
[448343     55      9      0]
[19559    70     5     0]
[127780    315     11      0]
[170172     45      8      0]
[321973     75      7      0]
[215473     50      9      0]
[58635    65    10     0]
[110682     55      6      0]
[54963   100    11     0]
[219561     30      8      0]
[441526     10      8      0]
[175916     40      6      0]
[96041    11     4     1]
[173461     40      9      0]
[418946      7      3      1]
[5038   60   10 

[36171    21     8     0]
[153774     20      7      0]
[319810     40      4      0]
[64500     5     7     0]
[291171     40      9      0]
[213389     20      6      0]
[362719     35     11      0]
[225559     25      7      0]
[289614     10     11      0]
[93173    75    16     0]
[292508    100     11      0]
[438624     20      8      0]
[193167     90     13      0]
[343546     90     11      0]
[371382     30      8      0]
[39623    80     9     0]
[140997     10     11      0]
[146423     80      9      0]
[168560     40      6      0]
[512375     25     10      0]
[337408     30      6      0]
[205257     80     13      0]
[389158     40      9      0]
[362991     10      5      1]
[493022     25      3      0]
[14178    10     3     1]
[378369     20     10      0]
[395272     10      4      1]
[9823   65    7    0]
[431624     50     15      0]
[3514    0   11    0]
[189389     45      7      0]
[26926    45     5     0]
[22680    50     7     0]
[211178     15      9   

[276200     50      9      0]
[517418      5      7      0]
[207088     65      9      0]
[261959     30     11      0]
[64566    30     7     0]
[52413    60    16     0]
[285566      2      5      1]
[259684    160     18      0]
[189681     35      9      0]
[252486     50     11      0]
[299155     40     10      0]
[375208     40      4      0]
[279343     30      8      0]
[135826     55      8      0]
[61911    40     5     0]
[37437    25    10     0]
[237757     45      8      0]
[368672     70      5      0]
[489497    145     12      0]
[232767     65      3      0]
[182246     25      8      0]
[199108     25      7      0]
[375017     45     15      0]
[312352     30     10      0]
[125017     50     10      0]
[38155     5     5     1]
[101943      5      9      0]
[11848    35    13     0]
[100248     55     10      0]
[14651    30     7     0]
[265925     27      6      0]
[283773     40      8      0]
[146828     30      4      0]
[231581     38     13      0]
[80345  

[410496     70     19      0]
[118367     60      6      0]
[53915    75    17     0]
[174730     30     11      0]
[496173     95     18      0]
[39229    60     9     0]
[397057     10      7      0]
[466438     25     10      0]
[357985     10      4      1]
[174765     35      6      0]
[426851      5      3      1]
[206493     35     12      0]
[316552     15     11      0]
[11565    10     6     0]
[3203   25    7    0]
[411494     25     11      0]
[267705    105     16      0]
[332728     65     10      0]
[180436     40      8      0]
[293942     75     11      0]
[85654    75     8     0]
[262768     10      4      1]
[360574     55      5      0]
[442876     40      6      0]
[177854     30      7      0]
[446062     15      8      0]
[353587     20      7      0]
[414756     60     10      0]
[122378     90     13      0]
[59711   300     5     0]
[99112    25    13     0]
[503499    280      9      0]
[7627  130    5    0]
[233205     20     10      0]
[115692     35      

[83988    23     8     0]
[25856    45    12     0]
[422048     10      5      1]
[153968     70     10      0]
[483703     30     10      0]
[326912     65     14      0]
[329754     20      9      0]
[320666     22     11      0]
[180943     35     10      0]
[316337     60     16      0]
[400554     90     11      0]
[317522     20      5      1]
[440740     50     17      0]
[363581    105      6      0]
[381464      5      8      0]
[59365    11     3     1]
[273543     75      7      0]
[283724    115     10      0]
[62057     4     4     1]
[382713    200     10      0]
[320527    320     18      0]
[295092     10      5      1]
[16075    52    10     0]
[435042   1470     14      0]
[298457     20      8      0]
[173004     45      8      0]
[388460     75      9      0]
[378882    150     26      0]
[164188      5      9      0]
[399980    320     20      0]
[236124     45     11      0]
[387154     75      6      0]
[186918     35     10      0]
[436823     25     14      0]


[270587    210     11      0]
[313007     70     17      0]
[449341     25      8      0]
[508734     13      4      1]
[77408    70    17     0]
[131601     60      8      0]
[377636     30     11      0]
[40829    30    10     0]
[323218    990      4      0]
[253252     40      6      0]
[192070     40      9      0]
[85641     3     5     1]
[44439    15    10     0]
[509335     40     21      0]
[171104     60     13      0]
[353426      5      5      1]
[512173     21      6      0]
[464917     30     12      0]
[96249     5     6     0]
[14614    40    10     0]
[72106    90     8     0]
[68719    40     7     0]
[410757    140     12      0]
[222151     35      8      0]
[116754     30      7      0]
[241714     40      9      0]
[137144     70      2      0]
[223077     40      7      0]
[17643   125     9     0]
[48192    70    10     0]
[359871     75     11      0]
[413438     20     11      0]
[406639    105      6      0]
[91192    20     6     0]
[494848   1560     13   

[69986    55    11     0]
[99734    10     8     0]
[200881      5      7      0]
[193674      1      3      1]
[455933     55     15      0]
[118993     30      6      0]
[150627    210      8      0]
[31820    15    13     0]
[85296    35    10     0]
[101119     60     15      0]
[52424   605     7     0]
[29181    85    10     0]
[367096     75      7      0]
[287097     20      8      0]
[98894    25     4     0]
[513187     65     10      0]
[61743    45     9     0]
[22875    20     3     1]
[186757     60     12      0]
[442233      5      5      1]
[247449     30     10      0]
[107426     40     10      0]
[27928     5     7     0]
[129173     20     11      0]
[205703     12      5      1]
[276656     40     10      0]
[435578     25     13      0]
[190488     25     18      0]
[180860     70     10      0]
[454462     30     10      0]
[125578     10      8      0]
[49792    60     7     0]
[404447     30     12      0]
[58775    90     9     0]
[124730     35     13      0

[115285     42      8      0]
[95315   105     7     0]
[187370     30     11      0]
[283094    225      9      0]
[479327     90     10      0]
[75259     5     5     1]
[475663     15      7      0]
[120086     40     12      0]
[232414     20     14      0]
[429984     30     13      0]
[182276    100     13      0]
[313562     20      8      0]
[358277     30      4      0]
[239725     40      8      0]
[298836     55     13      0]
[80950    55    11     0]
[272272     30      6      0]
[281182     60     13      0]
[418170     25      9      0]
[393479      5      2      1]
[41810    22     6     0]
[394767    210     10      0]
[48000   130     6     0]
[477483     50     12      0]
[494215    260      6      0]
[185860     60     13      0]
[47634   125     9     0]
[7636    0    9    0]
[164310     30      7      0]
[249432    270     14      0]
[450984      1      5      1]
[118639   1449     10      0]
[156302    250     12      0]
[159061     60     12      0]
[280472     

[318363     70     11      0]
[181230     55     16      0]
[121796     20      6      0]
[120253     40     10      0]
[307502     45     13      0]
[412684     25      7      0]
[350302     15     11      0]
[88372    40    13     0]
[334230     40      9      0]
[373607    270      7      0]
[57905    40     9     0]
[64460    25    10     0]
[188766     25     10      0]
[309194     40     11      0]
[439600     30      8      0]
[261664     45     13      0]
[519838     35     11      0]
[241342     30     12      0]
[402449     50     10      0]
[30669    60    12     0]
[181422     25      7      0]
[293420     35      9      0]
[286665    150      8      0]
[411266     35     13      0]
[47726    60    12     0]
[257010     60     11      0]
[307639     50     12      0]
[297392     20      6      0]
[460035     15     11      0]
[222431     40     12      0]
[384177   1920     12      0]
[38676    10     7     0]
[85249    30     9     0]
[352020    125     13      0]
[422410 

[170547     40     10      0]
[494206     20      7      0]
[284271     80     20      0]
[55682   105    19     0]
[19410   260    13     0]
[356945     85      7      0]
[128109      5      6      0]
[255248     40      9      0]
[66067    75    11     0]
[146014      5      8      0]
[68861    15     9     0]
[252249     90     13      0]
[152261     10      5      1]
[264340    200     13      0]
[11106    40    10     0]
[161070     60     12      0]
[219814      5      4      1]
[145662     20     12      0]
[148022     85     10      0]
[107017     65     12      0]
[9140  270    5    0]
[67314    35    10     0]
[64626    70    11     0]
[206730     45     13      0]
[90641  1445     8     0]
[135627     90     11      0]
[33978     5     5     1]
[34712     5     4     1]
[315722      9      5      1]
[45536    40    10     0]
[453927     20      8      0]
[61959   125     7     0]
[119978    310      5      0]
[205863     85      7      0]
[114139     30      9      0]
[35031

[44619    10     5     1]
[148768     90     12      0]
[444046     15      8      0]
[457895      4      4      1]
[163026     35      8      0]
[423432     30      7      0]
[208936     30      6      0]
[188655     85      6      0]
[427535     25     12      0]
[445112     10      4      1]
[24576   260     8     0]
[81025    40     7     0]
[166892     65      4      0]
[183714     45     10      0]
[422956     65      7      0]
[195339     53      7      0]
[314587     65     11      0]
[423255    120      9      0]
[294380     60      6      0]
[248953     45     10      0]
[150965     40      9      0]
[358163     50     12      0]
[277707     60      8      0]
[24525    10     8     0]
[140469     15     12      0]
[442905     30     10      0]
[191433      5      4      1]
[22988    18     7     0]
[334941     27      7      0]
[256456     11      5      1]
[393524     12      8      0]
[97086    95    15     0]
[475477     40      7      0]
[430000     50      5      0]
[176

[212775     55      8      0]
[21174    45    11     0]
[152082     60      8      0]
[428693      5      8      0]
[375066      3      4      1]
[91274    70     9     0]
[156993     55      8      0]
[57482    75    12     0]
[204710    117     12      0]
[39050    15     7     0]
[116986     60     13      0]
[70457   115    13     0]
[103388     10      6      0]
[244887     75      6      0]
[160698    500      8      0]
[263481     75     10      0]
[431493     30     12      0]
[35047    40     6     0]
[152000     35      7      0]
[254206     10      2      1]
[48075    25    12     0]
[208680     15      8      0]
[414553     30     12      0]
[461012     30      7      0]
[404000     90     13      0]
[131244     75      6      0]
[119596     10     10      0]
[12932     5     3     1]
[221049      9      7      0]
[40739    37    13     0]
[290522     75     15      0]
[133274     60      9      0]
[366725     35      7      0]
[116091     60     13      0]
[207944    110  

[51163    15     8     0]
[136193     75      9      0]
[412023      5      4      1]
[101468     70     12      0]
[267468     75     18      0]
[397520     30     13      0]
[306490     45     15      0]
[144766     70      8      0]
[394589     75     13      0]
[320081     28     14      0]
[165270    240     17      0]
[277066     60     11      0]
[266302     30     15      0]
[333608     65     16      0]
[408257     35      6      0]
[90732    45     9     0]
[249677     50     10      0]
[318156     45     14      0]
[400273      5      5      1]
[133749     40      7      0]
[16569    35    11     0]
[212612    450     12      0]
[224546      4      4      1]
[68910   500    14     0]
[388855     50      8      0]
[48510    70    10     0]
[281598     60      4      0]
[15306    20    11     0]
[48771    35     5     0]
[116465     10      8      0]
[370926     40      9      0]
[154194      2      3      1]
[102952     35     11      0]
[87883    27     7     0]
[274414    1

[41277    30    10     0]
[289712     75     11      0]
[133229     55      9      0]
[120876      4      3      1]
[459551     60     11      0]
[458411     20      7      0]
[364209      5      2      1]
[26994    45    13     0]
[104773    150     11      0]
[424275     70     11      0]
[247840    110     20      0]
[461337     40     11      0]
[21663    10     6     0]
[360873    180     18      0]
[193890     25      6      0]
[211586     60     13      0]
[283386    150     15      0]
[10749     6     6     0]
[456550     60      7      0]
[116676     50      9      0]
[180114     45     11      0]
[237398      3      8      0]
[463371     15     14      0]
[317818     40      7      0]
[32954    15     5     1]
[370788     15      7      0]
[481993     25     13      0]
[167851     30      9      0]
[263855     50     12      0]
[475731     60     19      0]
[308567     90      9      0]
[236004     15      7      0]
[238027     20      7      0]
[301021     35     14      0]


[351089     60     12      0]
[454946     30     11      0]
[7139    0    8    0]
[302963    150      9      0]
[298261     75     13      0]
[201391     11      5      1]
[368407     10     14      0]
[480044     75      9      0]
[125654     75      9      0]
[47058   100    12     0]
[222985    130     15      0]
[174815     10      2      1]
[26919   285    24     0]
[98789    35     9     0]
[161416     60     16      0]
[355973     45     11      0]
[87244    10    11     0]
[171036     21     16      0]
[375314     25      6      0]
[162773    135      6      0]
[251717     70      9      0]
[196707     45      5      0]
[456166     80     11      0]
[273947     30      7      0]
[178358     50      4      0]
[368675     15     10      0]
[373582     45      8      0]
[24087    50    10     0]
[248340     75      5      0]
[326684     20      9      0]
[129134    110      7      0]
[254697     70      8      0]
[491154      5      4      1]
[64861    60     7     0]
[25755    90

[79690    45    11     0]
[360930     25      8      0]
[222084     15      5      1]
[387813     35     12      0]
[360356    300     10      0]
[228141     30      7      0]
[181910      1      4      1]
[239589     35     12      0]
[11687    45     8     0]
[389375     45      5      0]
[113815     95     19      0]
[480423     37     12      0]
[446731     50      7      0]
[104204     70     10      0]
[397758     20     10      0]
[479817     40      9      0]
[294687     75      6      0]
[143003      5      3      1]
[332236    490      6      0]
[362375     26      7      0]
[357520     55      4      0]
[42525    15     9     0]
[376785     60     14      0]
[98191    15     7     0]
[318966    680      8      0]
[338316     35      8      0]
[215168     10      5      1]
[15153    35     9     0]
[121644     50     10      0]
[337580     30     11      0]
[64508    20     6     0]
[255887     35     16      0]
[309310     45     13      0]
[168154     14      4      1]
[256

[60254    25    11     0]
[107209    120     11      0]
[71400     5     5     1]
[249680     60     12      0]
[353548     90     10      0]
[201836     25      9      0]
[268020     70      5      0]
[303013     10      8      0]
[187184      5     10      0]
[431132     40     16      0]
[38959    15     3     1]
[16827    13     6     0]
[134428     20      7      0]
[178378     70     16      0]
[80565   120     6     0]
[58881    45     9     0]
[337738     95     13      0]
[242330     35     14      0]
[129072    110      9      0]
[54174    60     5     0]
[23605   180     8     0]
[276691     35      9      0]
[17015    20    11     0]
[84773    25     7     0]
[221975      1      2      1]
[162824     50      8      0]
[110548    105     19      0]
[304705     60     13      0]
[188173      5      2      1]
[60268    30    15     0]
[375628     25      3      0]
[414920     10      6      0]
[768  60  12   0]
[217501     52     13      0]
[263007     60      9      0]
[16261

[327252     30      7      0]
[228239     40     13      0]
[269162     10      5      1]
[72019    30     4     0]
[194517    130     11      0]
[255208     65     12      0]
[57156    30     9     0]
[50331   135    13     0]
[123866     30      8      0]
[233487     60     10      0]
[287211     90     10      0]
[115213    145      8      0]
[324911     65     16      0]
[470329     30     12      0]
[196015     85      8      0]
[88736    15    10     0]
[274601     25      9      0]
[83885    80    11     0]
[322647     20      5      1]
[180716     21      6      0]
[89641    40    11     0]
[358238     20      7      0]
[45549    10     3     1]
[438760     45     14      0]
[306505     20      7      0]
[340609     65     12      0]
[333291     70      9      0]
[31012   180    10     0]
[353513    120     11      0]
[217136     70     21      0]
[31167    55     9     0]
[261914     70     10      0]
[185885    100     18      0]
[71040    25     8     0]
[54182    50    10  

[490161     55     10      0]
[346223    660     22      0]
[156305     30      5      0]
[75570    80     8     0]
[298696     20      7      0]
[205067     70      2      0]
[26118    40     7     0]
[507398     30     15      0]
[47515    25     8     0]
[42507    60     8     0]
[67745    55    13     0]
[138992     20      5      1]
[407817     35      8      0]
[136108     20     11      0]
[244333    115      7      0]
[93125    35     7     0]
[216431     36      5      0]
[354342     32     11      0]
[74772    45    18     0]
[176208    490      7      0]
[29720   730     7     0]
[85819    25    10     0]
[129458     20     10      0]
[194075     20     10      0]
[231487     10      4      1]
[309606     40     14      0]
[333070     30     10      0]
[51555    30    21     0]
[533 196   8   0]
[203481     40      7      0]
[89780    35    14     0]
[12166    60    12     0]
[109880     45      8      0]
[97038   120     4     0]
[345300    160     11      0]
[457517     15

[201768     25      4      0]
[350997     30     12      0]
[284101     30     14      0]
[18555    20    22     0]
[458078      1      2      1]
[462296     25      5      0]
[83054    10     9     0]
[48418    75    19     0]
[195188     10      6      0]
[211249      2      3      1]
[13304    55     8     0]
[328523     60     10      0]
[213508     20     14      0]
[439595     35     12      0]
[282928     40      8      0]
[485684     25     12      0]
[137823     15      9      0]
[3444  380   10    0]
[497569     46      9      0]
[119203     20     13      0]
[271620     23      3      0]
[245542     25     13      0]
[141503     30      5      0]
[347225     80      9      0]
[403157    150      8      0]
[364513      5      6      0]
[516377      5      1      1]
[181182     30      7      0]
[169876     40      8      0]
[270488     50      8      0]
[482780     35     13      0]
[117040     40     12      0]
[319697     75      9      0]
[157904     40      5      0]
[386

[16425    65     8     0]
[78338    60    11     0]
[169811     90     16      0]
[423551      5      5      1]
[202460     50      8      0]
[10290    57    12     0]
[502245     13      3      1]
[68026    10     7     0]
[20644    60    12     0]
[24082    75     8     0]
[199940     65      7      0]
[357069     30     12      0]
[275924    375      6      0]
[219649    110     12      0]
[11526    10     8     0]
[460929    245      5      0]
[120890     10     12      0]
[336837     70     13      0]
[320466     50      9      0]
[504046      2      4      1]
[464472   2885      4      0]
[466072     90     12      0]
[106094     60      7      0]
[418076     90     12      0]
[270231     45      9      0]
[261752     75     10      0]
[104529     75     12      0]
[395052     30     14      0]
[464755     45      5      0]
[89059    95    10     0]
[153789     10      8      0]
[235039     75      5      0]
[81422    85     9     0]
[370775     23     15      0]
[56806   300    

[45907   321    11     0]
[153528     70      9      0]
[62747    25    11     0]
[334534     35     10      0]
[78161    35     6     0]
[18254   220    12     0]
[34218    10     5     1]
[260297    185      4      0]
[80144    40    13     0]
[500868     70      7      0]
[463948     60      9      0]
[194487     60      5      0]
[481598     20     11      0]
[119772     25      5      0]
[181840     90     12      0]
[439144     20      8      0]
[190185    135      3      0]
[253918     40     13      0]
[306317     30      8      0]
[208746     75      8      0]
[175632      9      2      1]
[332476     70     12      0]
[137629     32     11      0]
[229186     30     10      0]
[450591     75     15      0]
[361613     50     17      0]
[227602   1465     11      0]
[228442    500      9      0]
[518434     75     12      0]
[150890     70     11      0]
[61471     5     3     1]
[128647     65     14      0]
[350765     15      6      0]
[63431    65     9     0]
[302464     

[30530   105     9     0]
[110630     30     12      0]
[222869     40      9      0]
[392509     22      9      0]
[318887     55      8      0]
[32550    60    11     0]
[85286   555     7     0]
[136948     60     17      0]
[72308    70    13     0]
[294141     20      7      0]
[249020     35      5      0]
[209492     35     13      0]
[17833    45     8     0]
[158480     75     12      0]
[235894     90      8      0]
[80038    30    18     0]
[369121     55     12      0]
[395405    185      4      0]
[392057     25      7      0]
[389300      2      4      1]
[319830      8      8      0]
[191334     55      9      0]
[383548     60     14      0]
[471932     40      7      0]
[110931     53     10      0]
[125519     55      5      0]
[58263   120     6     0]
[331053     75      8      0]
[107712     45     13      0]
[488750     18     10      0]
[465062     95     14      0]
[83034   190     6     0]
[93606     5     5     1]
[429706    110     12      0]
[10378    30    

[116582     36     12      0]
[441963     21      5      0]
[88945    22     6     0]
[299710     45      9      0]
[243644     30      9      0]
[497777     20      5      1]
[254807     35     11      0]
[260110    730      9      0]
[273859     70     19      0]
[390440     70      6      0]
[46098   120    13     0]
[22269    65     7     0]
[415279     80     14      0]
[118450     32      7      0]
[212160     65      7      0]
[73146    35    13     0]
[495308     50     16      0]
[133679     35      9      0]
[228918    100      9      0]
[391265     30     10      0]
[261311     15      4      1]
[343723     10      6      0]
[68088    30     9     0]
[50890   315     6     0]
[7497    0   10    0]
[216860     30     10      0]
[121921     35      8      0]
[204987     20      7      0]
[142850     40     13      0]
[212739   1590      4      0]
[268387     40      9      0]
[342727     75     11      0]
[153284     80      9      0]
[388861     33     12      0]
[23674    65

[119688     85     11      0]
[212854     20     10      0]
[351429     23      4      0]
[313875     10      8      0]
[89660    65     7     0]
[291493      1      2      1]
[208326     30      9      0]
[39642    15     5     1]
[312693    375      9      0]
[44564    70     7     0]
[80267   140     9     0]
[469117     55     12      0]
[355406     35     11      0]
[54047    22     8     0]
[199055     70      8      0]
[155744     50      9      0]
[232757    190      3      0]
[224713     45     10      0]
[82396    40     7     0]
[245103     20     11      0]
[360925     40      5      0]
[319711      5      6      0]
[48208    80    13     0]
[234759     25      3      0]
[301648    190      8      0]
[226501     35     11      0]
[59610    50    11     0]
[107552     25      6      0]
[403421     44     11      0]
[284708     40     10      0]
[409817     45      5      0]
[46859    40    14     0]
[483631     22      4      0]
[315377     20      9      0]
[70437    40    

[177668     20      9      0]
[83806    30    11     0]
[126231     90      5      0]
[177972     25      9      0]
[21830    70    10     0]
[488614     11      9      0]
[309874     11      6      0]
[237134     23     10      0]
[165275      9      4      1]
[423983     35      8      0]
[337102     60     16      0]
[116295     15     10      0]
[379846     19      8      0]
[240691     25      5      0]
[344716     20      6      0]
[391449     45      7      0]
[398572     50     10      0]
[142588    125      6      0]
[129622     50      9      0]
[162484     15      9      0]
[41616    45     5     0]
[94309    65     9     0]
[402725     10      7      0]
[254309     60     10      0]
[230416     85      5      0]
[78339   360    26     0]
[122008     40      7      0]
[102901     75     14      0]
[194108     30      3      0]
[210427     10      8      0]
[332822     60      8      0]
[73061    30    12     0]
[68098    60    11     0]
[281290     15      9      0]
[53058  

[430537     30      9      0]
[212898     40     10      0]
[91491    10     8     0]
[127497     25      8      0]
[93753    15     4     1]
[464697     27      6      0]
[391539     15      4      1]
[314919     25      7      0]
[159060     20     10      0]
[42603    60     7     0]
[475390     60     14      0]
[91902    35    12     0]
[201483     40     11      0]
[136457     40      8      0]
[17620     7     5     1]
[107429     65     12      0]
[49923    35    10     0]
[223776    100     13      0]
[39946     4     5     1]
[329288    210     12      0]
[59025     5     5     1]
[499434     22     10      0]
[89800    35    10     0]
[61678    30     5     0]
[70826   140    13     0]
[81155   140     8     0]
[41561    90    15     0]
[136403    500     18      0]
[151018     10      3      1]
[69365    10     6     0]
[84064    50     7     0]
[512826     30     11      0]
[99265    18     6     0]
[76414    30     6     0]
[206765     70     11      0]
[287581     25    

[223667     25     14      0]
[295737     40      4      0]
[244123      2      3      1]
[14663    80     4     0]
[285491     60      6      0]
[258809    115     15      0]
[347010     45      9      0]
[186118     70      6      0]
[384230    120     11      0]
[251066     20      9      0]
[63612    60     9     0]
[148318   1455      3      0]
[241712      5      5      1]
[401098     35      9      0]
[17271    55     8     0]
[374207     12     10      0]
[69407    70    11     0]
[238286      2      6      0]
[319005     40      8      0]
[400544     45      6      0]
[404071     90     14      0]
[69516   495     9     0]
[215684     45     14      0]
[186553    270     15      0]
[150758     10      6      0]
[194195    100     11      0]
[55606     6     4     1]
[312723    240     14      0]
[231626     55      8      0]
[71952   105    12     0]
[405058     65      7      0]
[113060     55     14      0]
[101056     70      7      0]
[411594     30      7      0]
[359395 

[173916     35      9      0]
[108842     45     14      0]
[74807    20    13     0]
[483705      5      7      0]
[51356    45    11     0]
[124597    186      4      0]
[387582     85     10      0]
[485518     30     14      0]
[40543    30     4     0]
[307267    480     12      0]
[58178    35    12     0]
[85854    29    11     0]
[104023     10      8      0]
[69352    40    12     0]
[443827     60      7      0]
[100723     45     11      0]
[532289     10      5      1]
[217965     18      9      0]
[68846    60     9     0]
[261543     31     14      0]
[75235   120    10     0]
[14752    55     8     0]
[167384     20      6      0]
[359272     15      9      0]
[306892     35     16      0]
[226695     35     11      0]
[483807     15     13      0]
[15822    55     5     0]
[129954     50      9      0]
[361385    750     10      0]
[375730     22     13      0]
[353793      5      8      0]
[11197    22     8     0]
[248134     30     14      0]
[207702     35     14   

[115764    195     11      0]
[190926     15      3      1]
[470292     26     10      0]
[158237    165      9      0]
[71659   110    12     0]
[486567     25     11      0]
[385221    435      8      0]
[243406     15     13      0]
[150141     20      9      0]
[220644     35      6      0]
[134747     80      9      0]
[307667     35      6      0]
[61831    40     9     0]
[69706    10     6     0]
[524992     30     13      0]
[460246     30     13      0]
[263517     75     10      0]
[413380     20      7      0]
[367876     45     11      0]
[449647     30      8      0]
[76559   185     3     0]
[86830    70    12     0]
[281585     45     12      0]
[467495     50      8      0]
[472043     25     13      0]
[63522    45    12     0]
[169800    250      7      0]
[9407   65    7    0]
[125080      8      6      0]
[47943   150    22     0]
[368667    240     10      0]
[465  25   4   0]
[135880     20     10      0]
[32125    65    10     0]
[489145     30     13      0]
[3

[288075     35      8      0]
[437044     60     11      0]
[159523     30      6      0]
[317556      5      6      0]
[85442    25     7     0]
[514721     40      9      0]
[179366     65     15      0]
[338551     45      9      0]
[70303    25     8     0]
[289781     60      7      0]
[152549     27     10      0]
[383282     30      8      0]
[157584      3      3      1]
[353577   1500     12      0]
[2893   65   11    0]
[357474      6      7      0]
[51469    20     6     0]
[133199     30     10      0]
[457921     30     12      0]
[325674      5      8      0]
[217026     20     13      0]
[475161     30     13      0]
[460882      5      9      0]
[359146    120     10      0]
[34623    75    12     0]
[201855    135      3      0]
[50585   200     7     0]
[336769     35     20      0]
[351564      7      4      1]
[218240     70      6      0]
[166716     30      8      0]
[400783     45     14      0]
[346844     10      5      1]
[121278     17      9      0]
[164007 

13. Выведите процент "простых" рецептов в датасете

In [77]:
print(np.sum(arr_simple, axis=0)[3]/arr_simple.shape[0]*100)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [8]:
#первый элемент на оси ноль - группа 0
#второй элемент на оси ноль - группа 1 
#третий элемент на оси ноль - группа 2
arr_axis_0_gp_1 = arr[arr[:, 1] < 10]
print(arr_axis_0_gp_1.shape)
arr_axis_0_gp_2 = arr[(arr[:, 1] >= 10) & (arr[:, 1] < 20)]
print(arr_axis_0_gp_2.shape)
arr_axis_0_gp_3 = arr[arr[:, 1] > 20]
print(arr_axis_0_gp_3.shape)
print()
arr_3D = np.stack((arr_axis_0_gp_1, arr_axis_0_gp_2[:7588], arr_axis_0_gp_3[:7588]))
print(arr_3D.shape)
print()
print(arr_3D)

(7588, 3)
(12661, 3)
(73350, 3)

(3, 7588, 3)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      0      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [ 24549     70      6]
  [449468     50     11]
  [ 28830     65     13]]]
